[package]
name = "rgpu"
version = "0.1.0"
edition = "2024"

[dependencies]
ash = "0.38"
ash-window = "0.13"
raw-window-handle = { version = "0.6", features = ["std"] }
thiserror = "2"
tracing = "0.1"
